apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-processor-2281
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/service-processor-2281
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
